import React, { useState } from 'react';
import { Download, Copy, Check, FileCode, Printer, X, Sparkles } from 'lucide-react';

export default function ExportModal({ data, isOpen, onClose }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !data) return None;

  const generateMarkdown = () => {
    return `# Architecture Report: ${data.project_name || 'Software Project'}

## Executive Summary
${data.summary || 'N/A'}

## Recommended Architecture Pattern
**Style**: ${data.architecture_style || 'N/A'}

## Technology Stack Recommendations
- **Frontend Framework**: ${data.frontend?.name} (${data.frontend?.description})
- **Backend API Engine**: ${data.backend?.name} (${data.backend?.description})
- **Database Strategy**: ${data.database?.name} (${data.database?.description})
- **Authentication**: ${data.authentication?.name} (${data.authentication?.description})
- **Cloud Infrastructure**: ${data.deployment?.name} (${data.deployment?.description})

## Project Timeline Roadmap
${data.timeline?.map(t => `### ${t.phase} (${t.duration})\n${t.milestones?.map(m => `- ${m}`).join('\n')}`).join('\n\n')}

## Risk Analysis Matrix
${data.risk_analysis?.map(r => `- **${r.risk}** [Impact: ${r.impact} | Probability: ${r.probability}]\n  Mitigation: ${r.mitigation}`).join('\n\n')}

---
*Generated by AI Solution Architect powered by Google Gemini AI*
`;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const jsonStr = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(data.project_name || 'architecture').toLowerCase().replace(/\s+/g, '_')}_spec.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrintPDF = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-fadeIn">
      <div className="glass-panel w-full max-w-lg p-6 rounded-2xl border border-slate-700 shadow-2xl relative">
        
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors"
        >
          <X className="h-5 w-5" />
        </button>

        <div className="flex items-center gap-3 mb-4">
          <div className="p-3 rounded-xl bg-indigo-600/20 text-indigo-400 border border-indigo-500/30">
            <Download className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Export Architecture Spec</h3>
            <p className="text-xs text-slate-400">Download or copy report for project documentation</p>
          </div>
        </div>

        <div className="space-y-3 my-6">
          <button
            onClick={handleCopyMarkdown}
            className="w-full flex items-center justify-between p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-indigo-500/40 hover:bg-slate-850 transition-all text-sm font-medium text-slate-200 group"
          >
            <div className="flex items-center gap-3">
              <FileCode className="h-5 w-5 text-cyan-400" />
              <div className="text-left">
                <div className="text-white font-semibold">Copy Markdown Documentation</div>
                <div className="text-xs text-slate-400">Formatted for README.md or GitHub Issues</div>
              </div>
            </div>
            {copied ? (
              <span className="flex items-center gap-1 text-xs text-emerald-400 font-bold">
                <Check className="h-4 w-4" /> Copied
              </span>
            ) : (
              <Copy className="h-4 w-4 text-slate-400 group-hover:text-white" />
            )}
          </button>

          <button
            onClick={handleDownloadJSON}
            className="w-full flex items-center justify-between p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-indigo-500/40 hover:bg-slate-850 transition-all text-sm font-medium text-slate-200 group"
          >
            <div className="flex items-center gap-3">
              <Download className="h-5 w-5 text-indigo-400" />
              <div className="text-left">
                <div className="text-white font-semibold">Download Raw JSON</div>
                <div className="text-xs text-slate-400">Machine-readable specification for tools</div>
              </div>
            </div>
            <Download className="h-4 w-4 text-slate-400 group-hover:text-white" />
          </button>

          <button
            onClick={handlePrintPDF}
            className="w-full flex items-center justify-between p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-indigo-500/40 hover:bg-slate-850 transition-all text-sm font-medium text-slate-200 group"
          >
            <div className="flex items-center gap-3">
              <Printer className="h-5 w-5 text-purple-400" />
              <div className="text-left">
                <div className="text-white font-semibold">Print / Save as PDF</div>
                <div className="text-xs text-slate-400">Generates printable browser view</div>
              </div>
            </div>
            <Printer className="h-4 w-4 text-slate-400 group-hover:text-white" />
          </button>
        </div>

        <div className="flex justify-end pt-2 border-t border-slate-800">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-slate-300 hover:text-white rounded-lg bg-slate-800 hover:bg-slate-700 transition-colors"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
}
